@startuml
abstract class com.pluralsight.delishop.backend.PremiumTopping {
~ double price
}

abstract class com.pluralsight.delishop.backend.Addon {
}
class com.pluralsight.delishop.backend.Sandwich {
# ArrayList<Topping> toppings
# boolean isToasted
# BreadType breadType
# SandwichSize sandwichSize
# double price
+ SandwichSize getSandwichSize()
+ void addTopping(Topping)
+ double getPrice()
}


abstract class com.pluralsight.delishop.backend.Product {
+ {abstract}double getPrice()
}

class com.pluralsight.delishop.backend.Cheese {
- TypeOfCheese typeOfCheese
+ double getPrice()
}


class com.pluralsight.delishop.backend.Chips {
# String name
+ String getName()
+ double getPrice()
}


class com.pluralsight.delishop.backend.Drink {
- DrinkSize drinkSize
# double price
+ double getPrice()
}


class com.pluralsight.delishop.backend.RegularTopping {
# RegularToppings regularTopping
+ RegularToppings getRegularTopping()
+ boolean hasExtra()
+ double getPrice()
}


class com.pluralsight.delishop.backend.Meat {
# Meat typeOfMeat
+ Meat getTypeOfMeat()
+ double getPrice()
}


abstract class com.pluralsight.delishop.backend.Topping {
# boolean hasExtra
# SandwichSize size
+ {abstract}double getPrice()
}


class com.pluralsight.delishop.backend.Order {
- ArrayList<Product> items
- double totalPrice
+ void addItem(Product)
+ Order printOrder()
+ double getTotalPrice()
}




com.pluralsight.delishop.backend.Topping <|-- com.pluralsight.delishop.backend.PremiumTopping
com.pluralsight.delishop.backend.Product <|-- com.pluralsight.delishop.backend.Addon
com.pluralsight.delishop.backend.Product <|-- com.pluralsight.delishop.backend.Sandwich
com.pluralsight.delishop.backend.PremiumTopping <|-- com.pluralsight.delishop.backend.Cheese
com.pluralsight.delishop.backend.Addon <|-- com.pluralsight.delishop.backend.Chips
com.pluralsight.delishop.backend.Addon <|-- com.pluralsight.delishop.backend.Drink
com.pluralsight.delishop.backend.Topping <|-- com.pluralsight.delishop.backend.RegularTopping
com.pluralsight.delishop.backend.PremiumTopping <|-- com.pluralsight.delishop.backend.Meat
@enduml