/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pluralsight.delishop.userinterface.mainscreen;

import com.pluralsight.delishop.backend.inventory.RegularToppings;
import com.pluralsight.delishop.userinterface.loginscreen.UserPassScreen;
import com.pluralsight.delishop.backend.*;
import org.w3c.dom.css.CSSFontFaceRule;
import org.w3c.dom.css.RGBColor;

import javax.swing.*;
import java.sql.Wrapper;
import java.util.ArrayList;
import java.util.List;

/**
 * @author proco
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    Order order = new Order();

    public MainScreen() {
        initComponents();

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserPassScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserPassScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserPassScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserPassScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
                    this.setVisible(true);
                    this.setLocationRelativeTo(null);
                }
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeOfBreadGroup = new javax.swing.ButtonGroup();
        sizeButtonGroup = new javax.swing.ButtonGroup();
        toastedGroup = new javax.swing.ButtonGroup();
        drinkSizesGroup = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        orderContainer = new javax.swing.JScrollPane();
        orderItems = new javax.swing.JLabel();
        allButtons = new javax.swing.JLayeredPane();
        emptyMenu = new javax.swing.JLayeredPane();
        buttonMenu = new javax.swing.JLayeredPane();
        sandwichButton = new javax.swing.JButton();
        chipsButton = new javax.swing.JButton();
        drinkButton = new javax.swing.JButton();
        checkoutButton = new javax.swing.JButton();
        drinkMenu = new javax.swing.JLayeredPane();
        drinkSizes = new javax.swing.JPanel();
        smallDrinkButton = new javax.swing.JRadioButton();
        largeDrinkButton = new javax.swing.JRadioButton();
        mediumDrinkButton = new javax.swing.JRadioButton();
        drinkType = new javax.swing.JTextField();
        addDrinkButton = new javax.swing.JButton();
        sandwichMenu = new javax.swing.JLayeredPane();
        typeOfBreadPanel = new javax.swing.JPanel();
        typeOfBreadLabel = new javax.swing.JLabel();
        ryeButton = new javax.swing.JRadioButton();
        wheatButton = new javax.swing.JRadioButton();
        wrapButton = new javax.swing.JRadioButton();
        whiteButton = new javax.swing.JRadioButton();
        sizeOfSandwichPanel = new javax.swing.JPanel();
        sizeOfSandwichLabel = new javax.swing.JLabel();
        fourInchButton = new javax.swing.JRadioButton();
        twelveInchButton = new javax.swing.JRadioButton();
        eightInchButton = new javax.swing.JRadioButton();
        premiumToppingPanel = new javax.swing.JPanel();
        preimumLabel = new javax.swing.JLabel();
        hamButton = new javax.swing.JToggleButton();
        salamiButton = new javax.swing.JToggleButton();
        steakButton = new javax.swing.JToggleButton();
        roastBeefButton = new javax.swing.JToggleButton();
        chickenButton = new javax.swing.JToggleButton();
        baconButton = new javax.swing.JToggleButton();
        americanButton = new javax.swing.JToggleButton();
        provoloneButton = new javax.swing.JToggleButton();
        cheddarButton = new javax.swing.JToggleButton();
        swissButton = new javax.swing.JToggleButton();
        regularToppingPanel = new javax.swing.JPanel();
        regularLabel1 = new javax.swing.JLabel();
        lettuceButton = new javax.swing.JToggleButton();
        pepperButton = new javax.swing.JToggleButton();
        onionButton = new javax.swing.JToggleButton();
        tomatoButton = new javax.swing.JToggleButton();
        jalepenoButton = new javax.swing.JToggleButton();
        cucumberButton = new javax.swing.JToggleButton();
        pickleButton = new javax.swing.JToggleButton();
        guacamoleButton = new javax.swing.JToggleButton();
        mushroomButton = new javax.swing.JToggleButton();
        saucePanel = new javax.swing.JPanel();
        regularLabel2 = new javax.swing.JLabel();
        mayoButton = new javax.swing.JToggleButton();
        mustardButton = new javax.swing.JToggleButton();
        ketchupButton = new javax.swing.JToggleButton();
        islandButton = new javax.swing.JToggleButton();
        ranchButton = new javax.swing.JToggleButton();
        vinaigretteButton = new javax.swing.JToggleButton();
        toastedPanel = new javax.swing.JPanel();
        regularLabel = new javax.swing.JLabel();
        yesToastedButton = new javax.swing.JRadioButton();
        noToastedButton = new javax.swing.JRadioButton();
        addSandwich = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Deli POS System");
        setResizable(false);
        setSize(new java.awt.Dimension(1920, 1080));

        jLayeredPane1.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane1.setOpaque(true);
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1920, 1080));

        orderContainer.setBackground(new java.awt.Color(200, 200, 200));
        orderContainer.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        orderItems.setText("Place Holder");
        orderContainer.setViewportView(orderItems);

        allButtons.setBackground(new java.awt.Color(200, 200, 200));
        allButtons.setForeground(new java.awt.Color(200, 200, 200));
        allButtons.setOpaque(true);
        allButtons.setPreferredSize(new java.awt.Dimension(1920, 1080));

        javax.swing.GroupLayout emptyMenuLayout = new javax.swing.GroupLayout(emptyMenu);
        emptyMenu.setLayout(emptyMenuLayout);
        emptyMenuLayout.setHorizontalGroup(
                emptyMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 996, Short.MAX_VALUE)
        );
        emptyMenuLayout.setVerticalGroup(
                emptyMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1230, Short.MAX_VALUE)
        );

        sandwichButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sandwichButton.setText("Sandwiches");
        sandwichButton.setToolTipText("");
        sandwichButton.setFocusable(false);
        sandwichButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sandwichButtonActionPerformed(evt);
            }
        });

        chipsButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chipsButton.setText("Chips");
        chipsButton.setFocusable(false);

        drinkButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        drinkButton.setText("Drinks");
        drinkButton.setFocusable(false);
        drinkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinkButtonActionPerformed(evt);
            }
        });

        checkoutButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        checkoutButton.setText("Checkout");
        checkoutButton.setToolTipText("");
        checkoutButton.setFocusable(false);

        smallDrinkButton.setText("Small");
        smallDrinkButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        smallDrinkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallDrinkButtonActionPerformed(evt);
            }
        });

        largeDrinkButton.setText("Large");
        largeDrinkButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        largeDrinkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largeDrinkButtonActionPerformed(evt);
            }
        });

        mediumDrinkButton.setText("Medium");
        mediumDrinkButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mediumDrinkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediumDrinkButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout drinkSizesLayout = new javax.swing.GroupLayout(drinkSizes);
        drinkSizes.setLayout(drinkSizesLayout);
        drinkSizesLayout.setHorizontalGroup(
                drinkSizesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(drinkSizesLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(smallDrinkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                                .addComponent(mediumDrinkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(largeDrinkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75))
        );
        drinkSizesLayout.setVerticalGroup(
                drinkSizesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(drinkSizesLayout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(drinkSizesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(smallDrinkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(largeDrinkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(mediumDrinkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(78, Short.MAX_VALUE))
        );

        drinkType.setText("Name of the Drink");
        drinkType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinkTypeActionPerformed(evt);
            }
        });

        addDrinkButton.setText("Add Drink");
        addDrinkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDrinkButtonActionPerformed(evt);
            }
        });

        drinkMenu.setLayer(drinkSizes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        drinkMenu.setLayer(drinkType, javax.swing.JLayeredPane.DEFAULT_LAYER);
        drinkMenu.setLayer(addDrinkButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout drinkMenuLayout = new javax.swing.GroupLayout(drinkMenu);
        drinkMenu.setLayout(drinkMenuLayout);
        drinkMenuLayout.setHorizontalGroup(
                drinkMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(drinkMenuLayout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addGroup(drinkMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(addDrinkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(drinkType, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(drinkSizes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(185, Short.MAX_VALUE))
        );
        drinkMenuLayout.setVerticalGroup(
                drinkMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(drinkMenuLayout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(drinkSizes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(drinkType, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(124, 124, 124)
                                .addComponent(addDrinkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(129, Short.MAX_VALUE))
        );

        typeOfBreadPanel.setBackground(new java.awt.Color(200, 200, 200));

        typeOfBreadLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        typeOfBreadLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        typeOfBreadLabel.setText("Type of Bread");

        ryeButton.setBackground(new java.awt.Color(255, 255, 255));
        typeOfBreadGroup.add(ryeButton);
        ryeButton.setText("Rye");
        ryeButton.setBorderPainted(true);
        ryeButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ryeButton.setOpaque(true);
        ryeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ryeButtonActionPerformed(evt);
            }
        });

        wheatButton.setBackground(new java.awt.Color(255, 255, 255));
        typeOfBreadGroup.add(wheatButton);
        wheatButton.setText("Wheat");
        wheatButton.setBorderPainted(true);
        wheatButton.setFocusable(false);
        wheatButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wheatButton.setOpaque(true);
        wheatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wheatButtonActionPerformed(evt);
            }
        });

        wrapButton.setBackground(new java.awt.Color(255, 255, 255));
        typeOfBreadGroup.add(wrapButton);
        wrapButton.setText("Wrap");
        wrapButton.setBorderPainted(true);
        wrapButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wrapButton.setOpaque(true);
        wrapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wrapButtonActionPerformed(evt);
            }
        });

        whiteButton.setBackground(new java.awt.Color(255, 255, 255));
        typeOfBreadGroup.add(whiteButton);
        whiteButton.setText("White");
        whiteButton.setBorderPainted(true);
        whiteButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        whiteButton.setOpaque(true);
        whiteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whiteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout typeOfBreadPanelLayout = new javax.swing.GroupLayout(typeOfBreadPanel);
        typeOfBreadPanel.setLayout(typeOfBreadPanelLayout);
        typeOfBreadPanelLayout.setHorizontalGroup(
                typeOfBreadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(typeOfBreadPanelLayout.createSequentialGroup()
                                .addContainerGap(38, Short.MAX_VALUE)
                                .addComponent(typeOfBreadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
                        .addGroup(typeOfBreadPanelLayout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addGroup(typeOfBreadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(typeOfBreadPanelLayout.createSequentialGroup()
                                                .addComponent(ryeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28)
                                                .addComponent(wrapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(typeOfBreadPanelLayout.createSequentialGroup()
                                                .addComponent(whiteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(wheatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        typeOfBreadPanelLayout.setVerticalGroup(
                typeOfBreadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(typeOfBreadPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(typeOfBreadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(typeOfBreadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(wheatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(whiteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(typeOfBreadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(wrapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ryeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(29, Short.MAX_VALUE))
        );

        sizeOfSandwichPanel.setBackground(new java.awt.Color(200, 200, 200));

        sizeOfSandwichLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        sizeOfSandwichLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sizeOfSandwichLabel.setText("Size of Sandwich");

        fourInchButton.setBackground(new java.awt.Color(255, 255, 255));
        sizeButtonGroup.add(fourInchButton);
        fourInchButton.setText("4''");
        fourInchButton.setBorderPainted(true);
        fourInchButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fourInchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourInchButtonActionPerformed(evt);
            }
        });

        twelveInchButton.setBackground(new java.awt.Color(255, 255, 255));
        sizeButtonGroup.add(twelveInchButton);
        twelveInchButton.setText("12''");
        twelveInchButton.setBorderPainted(true);
        twelveInchButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        twelveInchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twelveInchButtonActionPerformed(evt);
            }
        });

        eightInchButton.setBackground(new java.awt.Color(255, 255, 255));
        sizeButtonGroup.add(eightInchButton);
        eightInchButton.setText("8''");
        eightInchButton.setBorderPainted(true);
        eightInchButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eightInchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightInchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sizeOfSandwichPanelLayout = new javax.swing.GroupLayout(sizeOfSandwichPanel);
        sizeOfSandwichPanel.setLayout(sizeOfSandwichPanelLayout);
        sizeOfSandwichPanelLayout.setHorizontalGroup(
                sizeOfSandwichPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sizeOfSandwichPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(sizeOfSandwichLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 11, Short.MAX_VALUE))
                        .addGroup(sizeOfSandwichPanelLayout.createSequentialGroup()
                                .addGroup(sizeOfSandwichPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(sizeOfSandwichPanelLayout.createSequentialGroup()
                                                .addGap(95, 95, 95)
                                                .addComponent(eightInchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(twelveInchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(sizeOfSandwichPanelLayout.createSequentialGroup()
                                                .addGap(161, 161, 161)
                                                .addComponent(fourInchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sizeOfSandwichPanelLayout.setVerticalGroup(
                sizeOfSandwichPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sizeOfSandwichPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(sizeOfSandwichLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(fourInchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(sizeOfSandwichPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(eightInchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                                        .addComponent(twelveInchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(34, Short.MAX_VALUE))
        );

        premiumToppingPanel.setBackground(new java.awt.Color(200, 200, 200));

        preimumLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        preimumLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        preimumLabel.setText("Premium Toppings");

        hamButton.setText("Ham");
        hamButton.setFocusable(false);
        hamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hamButtonActionPerformed(evt);
            }
        });

        salamiButton.setText("Salami");
        salamiButton.setFocusable(false);
        salamiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salamiButtonActionPerformed(evt);
            }
        });

        steakButton.setText("Steak");
        steakButton.setFocusable(false);
        steakButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                steakButtonActionPerformed(evt);
            }
        });

        roastBeefButton.setText("Roast Beef");
        roastBeefButton.setFocusable(false);
        roastBeefButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roastBeefButtonActionPerformed(evt);
            }
        });

        chickenButton.setText("Chicken");
        chickenButton.setFocusable(false);
        chickenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chickenButtonActionPerformed(evt);
            }
        });

        baconButton.setText("Bacon");
        baconButton.setFocusable(false);
        baconButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baconButtonActionPerformed(evt);
            }
        });

        americanButton.setText("American");
        americanButton.setFocusable(false);
        americanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                americanButtonActionPerformed(evt);
            }
        });

        provoloneButton.setText("Provolone");
        provoloneButton.setFocusable(false);
        provoloneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provoloneButtonActionPerformed(evt);
            }
        });

        cheddarButton.setText("Cheddar");
        cheddarButton.setFocusable(false);
        cheddarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheddarButtonActionPerformed(evt);
            }
        });

        swissButton.setText("Swiss");
        swissButton.setFocusable(false);
        swissButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                swissButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout premiumToppingPanelLayout = new javax.swing.GroupLayout(premiumToppingPanel);
        premiumToppingPanel.setLayout(premiumToppingPanelLayout);
        premiumToppingPanelLayout.setHorizontalGroup(
                premiumToppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(premiumToppingPanelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(premiumToppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, premiumToppingPanelLayout.createSequentialGroup()
                                                .addGroup(premiumToppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(premiumToppingPanelLayout.createSequentialGroup()
                                                                .addComponent(chickenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(2, 2, 2))
                                                        .addGroup(premiumToppingPanelLayout.createSequentialGroup()
                                                                .addComponent(americanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(provoloneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(12, 12, 12)
                                                .addGroup(premiumToppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(premiumToppingPanelLayout.createSequentialGroup()
                                                                .addComponent(cheddarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(swissButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(premiumToppingPanelLayout.createSequentialGroup()
                                                                .addGap(3, 3, 3)
                                                                .addComponent(baconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, premiumToppingPanelLayout.createSequentialGroup()
                                                .addComponent(preimumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, premiumToppingPanelLayout.createSequentialGroup()
                                                .addComponent(steakButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(hamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(salamiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(roastBeefButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(12, 14, Short.MAX_VALUE))
        );
        premiumToppingPanelLayout.setVerticalGroup(
                premiumToppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(premiumToppingPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(preimumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(premiumToppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(hamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(salamiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(roastBeefButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(steakButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(premiumToppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(chickenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(baconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(premiumToppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(americanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(provoloneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cheddarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(swissButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(63, Short.MAX_VALUE))
        );

        hamButton.setEnabled(false);
        salamiButton.setEnabled(false);
        steakButton.setEnabled(false);
        roastBeefButton.setEnabled(false);
        chickenButton.setEnabled(false);
        baconButton.setEnabled(false);
        americanButton.setEnabled(false);
        provoloneButton.setEnabled(false);
        cheddarButton.setEnabled(false);
        swissButton.setEnabled(false);

        regularToppingPanel.setBackground(new java.awt.Color(200, 200, 200));

        regularLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        regularLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regularLabel1.setText("Regular Toppings");

        lettuceButton.setText("Lettuce");
        lettuceButton.setFocusable(false);
        lettuceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lettuceButtonActionPerformed(evt);
            }
        });

        pepperButton.setText("Peppers");
        pepperButton.setFocusable(false);
        pepperButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pepperButtonActionPerformed(evt);
            }
        });

        onionButton.setText("Onions");
        onionButton.setFocusable(false);
        onionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onionButtonActionPerformed(evt);
            }
        });

        tomatoButton.setText("Tomatoes");
        tomatoButton.setFocusable(false);
        tomatoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomatoButtonActionPerformed(evt);
            }
        });

        jalepenoButton.setText("Jalepenos");
        jalepenoButton.setFocusable(false);
        jalepenoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jalepenoButtonActionPerformed(evt);
            }
        });

        cucumberButton.setText("Cucumbers");
        cucumberButton.setFocusable(false);
        cucumberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cucumberButtonActionPerformed(evt);
            }
        });

        pickleButton.setText("Pickles");
        pickleButton.setFocusable(false);
        pickleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickleButtonActionPerformed(evt);
            }
        });

        guacamoleButton.setText("Guacamole");
        guacamoleButton.setFocusable(false);
        guacamoleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guacamoleButtonActionPerformed(evt);
            }
        });

        mushroomButton.setText("Mushrooms");
        mushroomButton.setFocusable(false);
        mushroomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mushroomButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout regularToppingPanelLayout = new javax.swing.GroupLayout(regularToppingPanel);
        regularToppingPanel.setLayout(regularToppingPanelLayout);
        regularToppingPanelLayout.setHorizontalGroup(
                regularToppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(regularToppingPanelLayout.createSequentialGroup()
                                .addGroup(regularToppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(regularToppingPanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(regularLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(regularToppingPanelLayout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addComponent(lettuceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(pepperButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(onionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tomatoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(regularToppingPanelLayout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addComponent(jalepenoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cucumberButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(pickleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(guacamoleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(regularToppingPanelLayout.createSequentialGroup()
                                                .addGap(172, 172, 172)
                                                .addComponent(mushroomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        regularToppingPanelLayout.setVerticalGroup(
                regularToppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(regularToppingPanelLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(regularLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addGroup(regularToppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lettuceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pepperButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(onionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tomatoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(regularToppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(regularToppingPanelLayout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addGroup(regularToppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jalepenoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cucumberButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(regularToppingPanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(regularToppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(guacamoleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(pickleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mushroomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(20, Short.MAX_VALUE))
        );

        lettuceButton.setEnabled(false);
        pepperButton.setEnabled(false);
        onionButton.setEnabled(false);
        tomatoButton.setEnabled(false);
        jalepenoButton.setEnabled(false);
        cucumberButton.setEnabled(false);
        pickleButton.setEnabled(false);
        guacamoleButton.setEnabled(false);
        mushroomButton.setEnabled(false);

        saucePanel.setBackground(new java.awt.Color(200, 200, 200));

        regularLabel2.setBackground(java.awt.Color.lightGray);
        regularLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        regularLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regularLabel2.setText("Sauces");

        mayoButton.setText("Mayo");
        mayoButton.setFocusable(false);
        mayoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mayoButtonActionPerformed(evt);
            }
        });

        mustardButton.setText("Mustard");
        mustardButton.setFocusable(false);
        mustardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mustardButtonActionPerformed(evt);
            }
        });

        ketchupButton.setText("Ketchup");
        ketchupButton.setFocusable(false);
        ketchupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ketchupButtonActionPerformed(evt);
            }
        });

        islandButton.setText("Thousand Island");
        islandButton.setFocusable(false);
        islandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                islandButtonActionPerformed(evt);
            }
        });

        ranchButton.setText("Ranch");
        ranchButton.setFocusable(false);
        ranchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ranchButtonActionPerformed(evt);
            }
        });

        vinaigretteButton.setText("Vinaigrette");
        vinaigretteButton.setFocusable(false);
        vinaigretteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vinaigretteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout saucePanelLayout = new javax.swing.GroupLayout(saucePanel);
        saucePanel.setLayout(saucePanelLayout);
        saucePanelLayout.setHorizontalGroup(
                saucePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, saucePanelLayout.createSequentialGroup()
                                .addContainerGap(11, Short.MAX_VALUE)
                                .addComponent(regularLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                        .addGroup(saucePanelLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(mayoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(mustardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ketchupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))
                        .addGroup(saucePanelLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(ranchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(islandButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(vinaigretteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        saucePanelLayout.setVerticalGroup(
                saucePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(saucePanelLayout.createSequentialGroup()
                                .addComponent(regularLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addGroup(saucePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(mayoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(mustardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ketchupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(saucePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(islandButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ranchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(vinaigretteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(17, Short.MAX_VALUE))
        );

        mayoButton.setEnabled(false);
        mustardButton.setEnabled(false);
        ketchupButton.setEnabled(false);
        islandButton.setEnabled(false);
        ranchButton.setEnabled(false);
        vinaigretteButton.setEnabled(false);

        toastedPanel.setBackground(new java.awt.Color(200, 200, 200));

        regularLabel.setBackground(java.awt.Color.lightGray);
        regularLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        regularLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regularLabel.setText("Toasted?");

        toastedGroup.add(yesToastedButton);
        yesToastedButton.setText("Yes");
        yesToastedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesToastedButtonActionPerformed(evt);
            }
        });

        toastedGroup.add(noToastedButton);
        noToastedButton.setText("No");
        noToastedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noToastedButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout toastedPanelLayout = new javax.swing.GroupLayout(toastedPanel);
        toastedPanel.setLayout(toastedPanelLayout);
        toastedPanelLayout.setHorizontalGroup(
                toastedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(toastedPanelLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(regularLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(17, Short.MAX_VALUE))
                        .addGroup(toastedPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(yesToastedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)
                                .addComponent(noToastedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44))
        );
        toastedPanelLayout.setVerticalGroup(
                toastedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(toastedPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(regularLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(toastedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(yesToastedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(noToastedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(56, Short.MAX_VALUE))
        );

        yesToastedButton.setEnabled(false);
        noToastedButton.setEnabled(false);

        addSandwich.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        addSandwich.setText("Add to Order");
        addSandwich.setFocusable(false);
        addSandwich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSandwichActionPerformed(evt);
            }
        });

        sandwichMenu.setLayer(typeOfBreadPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        sandwichMenu.setLayer(sizeOfSandwichPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        sandwichMenu.setLayer(premiumToppingPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        sandwichMenu.setLayer(regularToppingPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        sandwichMenu.setLayer(saucePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        sandwichMenu.setLayer(toastedPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        sandwichMenu.setLayer(addSandwich, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout sandwichMenuLayout = new javax.swing.GroupLayout(sandwichMenu);
        sandwichMenu.setLayout(sandwichMenuLayout);
        sandwichMenuLayout.setHorizontalGroup(
                sandwichMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sandwichMenuLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(sandwichMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(premiumToppingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(typeOfBreadPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(toastedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                .addGroup(sandwichMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(saucePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(regularToppingPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(sizeOfSandwichPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sandwichMenuLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addSandwich, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(307, 307, 307))
        );
        sandwichMenuLayout.setVerticalGroup(
                sandwichMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sandwichMenuLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(sandwichMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(typeOfBreadPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(sizeOfSandwichPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(sandwichMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(sandwichMenuLayout.createSequentialGroup()
                                                .addComponent(premiumToppingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(toastedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(sandwichMenuLayout.createSequentialGroup()
                                                .addComponent(regularToppingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(saucePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(50, 50, 50)
                                .addComponent(addSandwich, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(150, Short.MAX_VALUE))
        );

        addSandwich.setEnabled(false);

        buttonMenu.setLayer(sandwichButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        buttonMenu.setLayer(chipsButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        buttonMenu.setLayer(drinkButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        buttonMenu.setLayer(checkoutButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        buttonMenu.setLayer(drinkMenu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        buttonMenu.setLayer(sandwichMenu, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout buttonMenuLayout = new javax.swing.GroupLayout(buttonMenu);
        buttonMenu.setLayout(buttonMenuLayout);
        buttonMenuLayout.setHorizontalGroup(
                buttonMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(buttonMenuLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(buttonMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(sandwichButton, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                        .addComponent(drinkButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(chipsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(checkoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sandwichMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(31, Short.MAX_VALUE))
                        .addGroup(buttonMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(buttonMenuLayout.createSequentialGroup()
                                        .addGap(190, 190, 190)
                                        .addComponent(drinkMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(73, Short.MAX_VALUE)))
        );
        buttonMenuLayout.setVerticalGroup(
                buttonMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(buttonMenuLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(buttonMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sandwichMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(buttonMenuLayout.createSequentialGroup()
                                                .addComponent(sandwichButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(59, 59, 59)
                                                .addComponent(drinkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(77, 77, 77)
                                                .addComponent(chipsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(372, 372, 372)
                                                .addComponent(checkoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(buttonMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(buttonMenuLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(drinkMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(175, Short.MAX_VALUE)))
        );

        drinkMenu.setVisible(false);
        sandwichMenu.setVisible(false);

        allButtons.setLayer(emptyMenu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        allButtons.setLayer(buttonMenu, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout allButtonsLayout = new javax.swing.GroupLayout(allButtons);
        allButtons.setLayout(allButtonsLayout);
        allButtonsLayout.setHorizontalGroup(
                allButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(allButtonsLayout.createSequentialGroup()
                                .addComponent(buttonMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emptyMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(173, 173, 173))
        );
        allButtonsLayout.setVerticalGroup(
                allButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(buttonMenu)
                        .addGroup(allButtonsLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(emptyMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        emptyMenu.setVisible(true);

        jLayeredPane1.setLayer(orderContainer, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(allButtons, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
                jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(orderContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(allButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 1240, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
        );
        jLayeredPane1Layout.setVerticalGroup(
                jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(allButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(orderContainer)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        premiumButtonList = List.of(steakButton, hamButton, salamiButton, roastBeefButton, chickenButton, baconButton, americanButton, provoloneButton, cheddarButton, swissButton);
        regularToppingButtonList = List.of(islandButton, lettuceButton, pepperButton, onionButton, tomatoButton, jalepenoButton, cucumberButton, pickleButton, guacamoleButton, mushroomButton, mayoButton, mustardButton, ketchupButton, ranchButton, vinaigretteButton);
        toastedButtons = List.of(yesToastedButton, noToastedButton);
        pack();
    }// </editor-fold>//GEN-END:initComponents

    //    private List<JToggleButton> premiumButtonList = List.of(steakButton, hamButton, salamiButton, roastBeefButton, chickenButton, baconButton, americanButton, provoloneButton, cheddarButton, swissButton);
//    private List<JToggleButton> regularToppingButtonList = List.of(islandButton, lettuceButton, pepperButton, onionButton, tomatoButton, jalepenoButton, cucumberButton, pickleButton, guacamoleButton, mushroomButton, mayoButton, mustardButton, ketchupButton, ranchButton, vinaigretteButton);
//    private List<JRadioButton> toastedButtons = List.of(yesToastedButton, noToastedButton);
    private List<JToggleButton> premiumButtonList;
    private List<JToggleButton> regularToppingButtonList;
    private List<JRadioButton> toastedButtons;

    private Sandwich.SandwichSize sandwichSize;
    private Sandwich.BreadType breadType;
    private ArrayList<Topping> toppings = new ArrayList<>();
    private boolean isToasted;
    private boolean typeCheck, sizeCheck = false;
    private String drinkName;
    private Drink.DrinkSize drinkSize;

    private void sandwichButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sandwichButtonActionPerformed
        if (sandwichMenu.isVisible()) {
            //Turning off sandwich mode
            sandwichMenu.setVisible(false);
            emptyMenu.setVisible(true);
            drinkButton.setEnabled(true);
            chipsButton.setEnabled(true);
            checkoutButton.setEnabled(true);
        } else {
            //turning on sandwich mode
            sandwichMenu.setVisible(true);
            emptyMenu.setVisible(false);
            drinkButton.setEnabled(false);
            chipsButton.setEnabled(false);
            checkoutButton.setEnabled(false);
        }
    }//GEN-LAST:event_sandwichButtonActionPerformed

    Meat meat;

    private void addMeat(JToggleButton button, Meat.TypeOfMeat typeOfMeat) {
        if (button.isSelected()) {
            int extra = JOptionPane.showConfirmDialog(sandwichMenu, "Does the customer want extra?", "Extra", JOptionPane.YES_NO_OPTION);
            if (extra == 0) {
                meat = new Meat(typeOfMeat, sandwichSize, true);
                toppings.add(meat);
            } else {
                meat = new Meat(typeOfMeat, sandwichSize, false);
                toppings.add(meat);
            }
        } else {
            toppings.removeIf(t -> {
                try {
                    return ((Meat) t).getTypeOfMeat() == typeOfMeat;
                } catch (ClassCastException e) {
                    return false;
                }

            });
        }
        toppings.stream().forEach(t -> System.out.println(t.toString()));
    }

    Cheese cheese;

    private void addCheese(JToggleButton button, Cheese.TypeOfCheese typeOfCheese) {
        if (button.isSelected()) {
            int extra = JOptionPane.showConfirmDialog(sandwichMenu, "Does the customer want extra?", "Extra", JOptionPane.YES_NO_OPTION);
            if (extra == 0) {
                cheese = new Cheese(typeOfCheese, sandwichSize, true);
                toppings.add(cheese);
            } else {
                cheese = new Cheese(typeOfCheese, sandwichSize, false);
                toppings.add(cheese);
            }
        } else {
            toppings.removeIf(t -> {
                try {
                    return ((Cheese) t).getTypeOfCheese() == typeOfCheese;
                } catch (ClassCastException e) {
                    return false;
                }
            });
        }
        toppings.stream().forEach(t -> System.out.println(t.toString()));
    }

    RegularTopping regTopping;

    private void addRegTopping(JToggleButton button, RegularToppings topping) {
        if (button.isSelected()) {
            int extra = JOptionPane.showConfirmDialog(sandwichMenu, "Does the customer want extra?", "Extra", JOptionPane.YES_NO_OPTION);
            if (extra == 0) {
                regTopping = new RegularTopping(true, sandwichSize, topping);
                toppings.add(regTopping);
            } else {
                regTopping = new RegularTopping(false, sandwichSize, topping);
                toppings.add(regTopping);
            }
        } else {
            toppings.removeIf(t -> {
                try {
                    return ((RegularTopping) t).getRegularTopping() == topping;
                } catch (ClassCastException e) {
                    return false;
                }
            });

        }
        toppings.stream().forEach(t -> System.out.println(t.toString()));
    }

    private void steakButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_steakButtonActionPerformed
        addMeat(steakButton, Meat.TypeOfMeat.STEAK);
    }//GEN-LAST:event_steakButtonActionPerformed

    private void baconButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baconButtonActionPerformed
        addMeat(baconButton, Meat.TypeOfMeat.BACON);
    }//GEN-LAST:event_baconButtonActionPerformed

    private void americanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_americanButtonActionPerformed
        addCheese(americanButton, Cheese.TypeOfCheese.AMERICAN);
    }//GEN-LAST:event_americanButtonActionPerformed

    private void provoloneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provoloneButtonActionPerformed
        addCheese(provoloneButton, Cheese.TypeOfCheese.PROVOLONE);
    }//GEN-LAST:event_provoloneButtonActionPerformed

    private void cheddarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheddarButtonActionPerformed
        addCheese(cheddarButton, Cheese.TypeOfCheese.CHEDDAR);
    }//GEN-LAST:event_cheddarButtonActionPerformed

    private void swissButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_swissButtonActionPerformed
        addCheese(swissButton, Cheese.TypeOfCheese.SWISS);
    }//GEN-LAST:event_swissButtonActionPerformed


    private void tomatoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomatoButtonActionPerformed
        addRegTopping(tomatoButton, RegularToppings.TOMATOES);
    }//GEN-LAST:event_tomatoButtonActionPerformed

    private void onionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onionButtonActionPerformed
        addRegTopping(onionButton, RegularToppings.ONIONS);
    }//GEN-LAST:event_onionButtonActionPerformed

    private void pepperButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pepperButtonActionPerformed
        addRegTopping(pepperButton, RegularToppings.PEPPERS);
    }//GEN-LAST:event_pepperButtonActionPerformed

    private void lettuceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lettuceButtonActionPerformed
        addRegTopping(lettuceButton, RegularToppings.LETTUCE);
    }//GEN-LAST:event_lettuceButtonActionPerformed

    private void jalepenoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jalepenoButtonActionPerformed
        addRegTopping(jalepenoButton, RegularToppings.JALEPENOS);
    }//GEN-LAST:event_jalepenoButtonActionPerformed

    private void cucumberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cucumberButtonActionPerformed
        addRegTopping(cucumberButton, RegularToppings.CUCUMBERS);
    }//GEN-LAST:event_cucumberButtonActionPerformed

    private void pickleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickleButtonActionPerformed
        addRegTopping(pickleButton, RegularToppings.PICKLES);
    }//GEN-LAST:event_pickleButtonActionPerformed

    private void guacamoleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guacamoleButtonActionPerformed
        addRegTopping(guacamoleButton, RegularToppings.GUACAMOLE);
    }//GEN-LAST:event_guacamoleButtonActionPerformed

    private void mushroomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mushroomButtonActionPerformed
        addRegTopping(mushroomButton, RegularToppings.MUSHROOMS);
    }//GEN-LAST:event_mushroomButtonActionPerformed

    private void mayoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mayoButtonActionPerformed
        addRegTopping(mayoButton, RegularToppings.MAYO);
    }//GEN-LAST:event_mayoButtonActionPerformed

    private void mustardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mustardButtonActionPerformed
        addRegTopping(mustardButton, RegularToppings.MUSTARD);
    }//GEN-LAST:event_mustardButtonActionPerformed

    private void ketchupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ketchupButtonActionPerformed
        addRegTopping(ketchupButton, RegularToppings.KETCHUP);
    }//GEN-LAST:event_ketchupButtonActionPerformed

    private void islandButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_islandButtonActionPerformed
        addRegTopping(islandButton, RegularToppings.THOUSAND_ISLAND);
    }//GEN-LAST:event_islandButtonActionPerformed

    private void ranchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ranchButtonActionPerformed
        addRegTopping(ranchButton, RegularToppings.RANCH);
    }//GEN-LAST:event_ranchButtonActionPerformed

    private void vinaigretteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vinaigretteButtonActionPerformed
        addRegTopping(vinaigretteButton, RegularToppings.VINAIGRETTE);
    }//GEN-LAST:event_vinaigretteButtonActionPerformed

    private void hamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hamButtonActionPerformed
        addMeat(hamButton, Meat.TypeOfMeat.HAM);
    }//GEN-LAST:event_hamButtonActionPerformed

    private void salamiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salamiButtonActionPerformed
        addMeat(salamiButton, Meat.TypeOfMeat.SALAMI);
    }//GEN-LAST:event_salamiButtonActionPerformed

    private void roastBeefButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roastBeefButtonActionPerformed
        addMeat(roastBeefButton, Meat.TypeOfMeat.ROAST_BEEF);
    }//GEN-LAST:event_roastBeefButtonActionPerformed

    private void chickenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chickenButtonActionPerformed
        addMeat(chickenButton, Meat.TypeOfMeat.CHICKEN);
    }//GEN-LAST:event_chickenButtonActionPerformed

    private void whiteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whiteButtonActionPerformed
        breadType = Sandwich.BreadType.WHITE;
        typeCheck = true;
    }//GEN-LAST:event_whiteButtonActionPerformed

    private void wheatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wheatButtonActionPerformed
        breadType = Sandwich.BreadType.WHEAT;
        typeCheck = true;
    }//GEN-LAST:event_wheatButtonActionPerformed

    private void ryeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ryeButtonActionPerformed
        breadType = Sandwich.BreadType.RYE;
        typeCheck = true;
    }//GEN-LAST:event_ryeButtonActionPerformed

    private void wrapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wrapButtonActionPerformed
        breadType = Sandwich.BreadType.WRAP;
        typeCheck = true;
    }//GEN-LAST:event_wrapButtonActionPerformed

    private void fourInchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourInchButtonActionPerformed
        sandwichSize = Sandwich.SandwichSize.FOURINCH;
        toppings.clear();
        for (JToggleButton button : premiumButtonList) {
            button.setSelected(false);
        }
        for (JToggleButton button : regularToppingButtonList) {
            button.setSelected(false);
        }
        sizeCheck = true;
        setButtonsEnabled();
    }//GEN-LAST:event_fourInchButtonActionPerformed

    private void eightInchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightInchButtonActionPerformed
        sandwichSize = Sandwich.SandwichSize.EIGHTINCH;

        toppings.clear();
        for (JToggleButton button : premiumButtonList) {
            button.setSelected(false);
        }
        for (JToggleButton button : regularToppingButtonList) {
            button.setSelected(false);
        }
        sizeCheck = true;
        setButtonsEnabled();
    }//GEN-LAST:event_eightInchButtonActionPerformed

    private void twelveInchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twelveInchButtonActionPerformed
        sandwichSize = Sandwich.SandwichSize.TWELVEINCH;

        toppings.clear();
        for (JToggleButton button : premiumButtonList) {
            button.setSelected(false);
        }
        for (JToggleButton button : regularToppingButtonList) {
            button.setSelected(false);
        }
        sizeCheck = true;
        setButtonsEnabled();
    }//GEN-LAST:event_twelveInchButtonActionPerformed

    private void yesToastedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesToastedButtonActionPerformed
        isToasted = true;
        addSandwich.setEnabled(true);
    }//GEN-LAST:event_yesToastedButtonActionPerformed

    private void noToastedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noToastedButtonActionPerformed
        isToasted = false;
        addSandwich.setEnabled(true);
    }//GEN-LAST:event_noToastedButtonActionPerformed

    private void drinkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinkButtonActionPerformed
        if (drinkMenu.isVisible()) {
            //Turning off sandwich mode
            drinkMenu.setVisible(false);
            emptyMenu.setVisible(true);
            sandwichButton.setEnabled(true);
            chipsButton.setEnabled(true);
            checkoutButton.setEnabled(true);
        } else {
            //turning on sandwich mode
            drinkMenu.setVisible(true);
            emptyMenu.setVisible(false);
            sandwichButton.setEnabled(false);
            chipsButton.setEnabled(false);
            checkoutButton.setEnabled(false);
        }

    }//GEN-LAST:event_drinkButtonActionPerformed

    private void largeDrinkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largeDrinkButtonActionPerformed
        drinkSize = Drink.DrinkSize.LARGE;
    }//GEN-LAST:event_largeDrinkButtonActionPerformed

    private void smallDrinkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallDrinkButtonActionPerformed
        drinkSize = Drink.DrinkSize.SMALL;
    }//GEN-LAST:event_smallDrinkButtonActionPerformed

    private void mediumDrinkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediumDrinkButtonActionPerformed
        drinkSize = Drink.DrinkSize.MEDIUM;
    }//GEN-LAST:event_mediumDrinkButtonActionPerformed

    private void drinkTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinkTypeActionPerformed
        drinkName = drinkType.getText();
    }//GEN-LAST:event_drinkTypeActionPerformed

    private void addDrinkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDrinkButtonActionPerformed
        order.addItem(new Drink(drinkSize, drinkName));
    }//GEN-LAST:event_addDrinkButtonActionPerformed

    private void addSandwichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSandwichActionPerformed
        Sandwich sandwich = new Sandwich(sandwichSize, isToasted, breadType, toppings);
        order.addItem(sandwich);
        orderItems.setText(sandwich.toString());
    }//GEN-LAST:event_addSandwichActionPerformed


    private void setButtonsEnabled() {
        if (typeCheck && sizeCheck) {
            for (JToggleButton button : premiumButtonList) {
                button.setEnabled(true);
            }
            for (JToggleButton button : regularToppingButtonList) {
                button.setEnabled(true);
            }
            for (JRadioButton button : toastedButtons) {
                button.setEnabled(true);
            }
        }
    }

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDrinkButton;
    private javax.swing.JButton addSandwich;
    private javax.swing.JLayeredPane allButtons;
    private javax.swing.JToggleButton americanButton;
    private javax.swing.JToggleButton baconButton;
    private javax.swing.JLayeredPane buttonMenu;
    private javax.swing.JButton checkoutButton;
    private javax.swing.JToggleButton cheddarButton;
    private javax.swing.JToggleButton chickenButton;
    private javax.swing.JButton chipsButton;
    private javax.swing.JToggleButton cucumberButton;
    private javax.swing.JButton drinkButton;
    private javax.swing.JLayeredPane drinkMenu;
    private javax.swing.JPanel drinkSizes;
    private javax.swing.ButtonGroup drinkSizesGroup;
    private javax.swing.JTextField drinkType;
    private javax.swing.JRadioButton eightInchButton;
    private javax.swing.JLayeredPane emptyMenu;
    private javax.swing.JRadioButton fourInchButton;
    private javax.swing.JToggleButton guacamoleButton;
    private javax.swing.JToggleButton hamButton;
    private javax.swing.JToggleButton islandButton;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JToggleButton jalepenoButton;
    private javax.swing.JToggleButton ketchupButton;
    private javax.swing.JRadioButton largeDrinkButton;
    private javax.swing.JToggleButton lettuceButton;
    private javax.swing.JToggleButton mayoButton;
    private javax.swing.JRadioButton mediumDrinkButton;
    private javax.swing.JToggleButton mushroomButton;
    private javax.swing.JToggleButton mustardButton;
    private javax.swing.JRadioButton noToastedButton;
    private javax.swing.JToggleButton onionButton;
    private javax.swing.JScrollPane orderContainer;
    private javax.swing.JLabel orderItems;
    private javax.swing.JToggleButton pepperButton;
    private javax.swing.JToggleButton pickleButton;
    private javax.swing.JLabel preimumLabel;
    private javax.swing.JPanel premiumToppingPanel;
    private javax.swing.JToggleButton provoloneButton;
    private javax.swing.JToggleButton ranchButton;
    private javax.swing.JLabel regularLabel;
    private javax.swing.JLabel regularLabel1;
    private javax.swing.JLabel regularLabel2;
    private javax.swing.JPanel regularToppingPanel;
    private javax.swing.JToggleButton roastBeefButton;
    private javax.swing.JRadioButton ryeButton;
    private javax.swing.JToggleButton salamiButton;
    private javax.swing.JButton sandwichButton;
    private javax.swing.JLayeredPane sandwichMenu;
    private javax.swing.JPanel saucePanel;
    private javax.swing.ButtonGroup sizeButtonGroup;
    private javax.swing.JLabel sizeOfSandwichLabel;
    private javax.swing.JPanel sizeOfSandwichPanel;
    private javax.swing.JRadioButton smallDrinkButton;
    private javax.swing.JToggleButton steakButton;
    private javax.swing.JToggleButton swissButton;
    private javax.swing.ButtonGroup toastedGroup;
    private javax.swing.JPanel toastedPanel;
    private javax.swing.JToggleButton tomatoButton;
    private javax.swing.JRadioButton twelveInchButton;
    private javax.swing.ButtonGroup typeOfBreadGroup;
    private javax.swing.JLabel typeOfBreadLabel;
    private javax.swing.JPanel typeOfBreadPanel;
    private javax.swing.JToggleButton vinaigretteButton;
    private javax.swing.JRadioButton wheatButton;
    private javax.swing.JRadioButton whiteButton;
    private javax.swing.JRadioButton wrapButton;
    private javax.swing.JRadioButton yesToastedButton;
    // End of variables declaration//GEN-END:variables
    ;
}
