/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pluralsight.delishop.userinterface.mainscreen;

import com.pluralsight.delishop.backend.inventory.RegularToppings;
import com.pluralsight.delishop.userinterface.loginscreen.UserPassScreen;
import com.pluralsight.delishop.backend.*;

import javax.swing.*;
import java.util.ArrayList;

/**
 * @author proco
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    Order order = new Order();

    public MainScreen() {
        initComponents();

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserPassScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserPassScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserPassScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserPassScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
                    this.setVisible(true);
                    this.setLocationRelativeTo(null);
                }
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        orderContainer = new javax.swing.JScrollPane();
        allButtons = new javax.swing.JLayeredPane();
        emptyMenu = new javax.swing.JLayeredPane();
        buttonMenu = new javax.swing.JLayeredPane();
        sandwichButton = new javax.swing.JButton();
        chipsButton = new javax.swing.JButton();
        drinkButton = new javax.swing.JButton();
        checkoutButton = new javax.swing.JButton();
        sandwichMenu = new javax.swing.JLayeredPane();
        typeOfBreadPanel = new javax.swing.JPanel();
        ryeButton = new javax.swing.JButton();
        wrapButton = new javax.swing.JButton();
        wheatButton = new javax.swing.JButton();
        whiteButton = new javax.swing.JButton();
        typeOfBreadLabel = new javax.swing.JLabel();
        sizeOfSandwichPanel = new javax.swing.JPanel();
        twelveInchButton = new javax.swing.JButton();
        eightInchButton = new javax.swing.JButton();
        fourInchButton = new javax.swing.JButton();
        sizeOfSandwichLabel = new javax.swing.JLabel();
        premiumToppingPanel = new javax.swing.JPanel();
        preimumLabel = new javax.swing.JLabel();
        hamButton = new javax.swing.JToggleButton();
        salamiButton = new javax.swing.JToggleButton();
        steakButton = new javax.swing.JToggleButton();
        roastBeefButton = new javax.swing.JToggleButton();
        chickenButton = new javax.swing.JToggleButton();
        baconButton = new javax.swing.JToggleButton();
        americanButton = new javax.swing.JToggleButton();
        provoloneButton = new javax.swing.JToggleButton();
        cheddarButton = new javax.swing.JToggleButton();
        swissButton = new javax.swing.JToggleButton();
        regularToppingPanel = new javax.swing.JPanel();
        regularLabel1 = new javax.swing.JLabel();
        lettuceButton = new javax.swing.JToggleButton();
        pepperButton = new javax.swing.JToggleButton();
        onionButton = new javax.swing.JToggleButton();
        tomatoButton = new javax.swing.JToggleButton();
        jalepenoButton = new javax.swing.JToggleButton();
        cucumberButton = new javax.swing.JToggleButton();
        pickleButton = new javax.swing.JToggleButton();
        guacamoleButton = new javax.swing.JToggleButton();
        mushroomButton = new javax.swing.JToggleButton();
        saucePanel = new javax.swing.JPanel();
        regularLabel2 = new javax.swing.JLabel();
        mayoButton = new javax.swing.JToggleButton();
        mustardButton = new javax.swing.JToggleButton();
        ketchupButton = new javax.swing.JToggleButton();
        islandButton = new javax.swing.JToggleButton();
        ranchButton = new javax.swing.JToggleButton();
        vinaigretteButton = new javax.swing.JToggleButton();
        toastedPanel = new javax.swing.JPanel();
        regularLabel = new javax.swing.JLabel();
        noToastedButton = new javax.swing.JButton();
        yesToastedButton = new javax.swing.JButton();
        addSandwich = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Deli POS System");
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setResizable(false);
        setSize(new java.awt.Dimension(1920, 1080));

        jLayeredPane1.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane1.setOpaque(true);
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1920, 1080));

        orderContainer.setBackground(new java.awt.Color(200, 200, 200));
        orderContainer.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        allButtons.setBackground(new java.awt.Color(200, 200, 200));
        allButtons.setForeground(new java.awt.Color(200, 200, 200));
        allButtons.setOpaque(true);
        allButtons.setPreferredSize(new java.awt.Dimension(1920, 1080));

        javax.swing.GroupLayout emptyMenuLayout = new javax.swing.GroupLayout(emptyMenu);
        emptyMenu.setLayout(emptyMenuLayout);
        emptyMenuLayout.setHorizontalGroup(
            emptyMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 996, Short.MAX_VALUE)
        );
        emptyMenuLayout.setVerticalGroup(
            emptyMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1230, Short.MAX_VALUE)
        );

        sandwichButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sandwichButton.setText("Sandwiches");
        sandwichButton.setToolTipText("");
        sandwichButton.setFocusable(false);
        sandwichButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sandwichButtonActionPerformed(evt);
            }
        });

        chipsButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chipsButton.setText("Chips");
        chipsButton.setFocusable(false);

        drinkButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        drinkButton.setText("Drinks");
        drinkButton.setFocusable(false);

        checkoutButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        checkoutButton.setText("Checkout");
        checkoutButton.setToolTipText("");
        checkoutButton.setFocusable(false);

        typeOfBreadPanel.setBackground(new java.awt.Color(200, 200, 200));

        ryeButton.setText("Rye");
        ryeButton.setFocusable(false);
        ryeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ryeButtonActionPerformed(evt);
            }
        });

        wrapButton.setText("Wrap");
        wrapButton.setFocusable(false);

        wheatButton.setText("Wheat");
        wheatButton.setFocusable(false);

        whiteButton.setText("White");
        whiteButton.setFocusable(false);
        whiteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whiteButtonActionPerformed(evt);
            }
        });

        typeOfBreadLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        typeOfBreadLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        typeOfBreadLabel.setText("Type of Bread");

        javax.swing.GroupLayout typeOfBreadPanelLayout = new javax.swing.GroupLayout(typeOfBreadPanel);
        typeOfBreadPanel.setLayout(typeOfBreadPanelLayout);
        typeOfBreadPanelLayout.setHorizontalGroup(
            typeOfBreadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(typeOfBreadPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(typeOfBreadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, typeOfBreadPanelLayout.createSequentialGroup()
                        .addGroup(typeOfBreadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ryeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(whiteButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(typeOfBreadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wheatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wrapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, typeOfBreadPanelLayout.createSequentialGroup()
                        .addComponent(typeOfBreadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
        typeOfBreadPanelLayout.setVerticalGroup(
            typeOfBreadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(typeOfBreadPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(typeOfBreadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(typeOfBreadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(whiteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wheatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(typeOfBreadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ryeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wrapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        sizeOfSandwichPanel.setBackground(new java.awt.Color(200, 200, 200));

        twelveInchButton.setText("12 Inch");
        twelveInchButton.setFocusable(false);

        eightInchButton.setText("8 Inch");
        eightInchButton.setFocusable(false);

        fourInchButton.setText("4 Inch");
        fourInchButton.setFocusable(false);

        sizeOfSandwichLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        sizeOfSandwichLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sizeOfSandwichLabel.setText("Size of Sandwich");

        javax.swing.GroupLayout sizeOfSandwichPanelLayout = new javax.swing.GroupLayout(sizeOfSandwichPanel);
        sizeOfSandwichPanel.setLayout(sizeOfSandwichPanelLayout);
        sizeOfSandwichPanelLayout.setHorizontalGroup(
            sizeOfSandwichPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sizeOfSandwichPanelLayout.createSequentialGroup()
                .addGroup(sizeOfSandwichPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sizeOfSandwichPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sizeOfSandwichLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sizeOfSandwichPanelLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(sizeOfSandwichPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sizeOfSandwichPanelLayout.createSequentialGroup()
                                .addComponent(eightInchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(twelveInchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sizeOfSandwichPanelLayout.createSequentialGroup()
                                .addComponent(fourInchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)))))
                .addGap(0, 11, Short.MAX_VALUE))
        );
        sizeOfSandwichPanelLayout.setVerticalGroup(
            sizeOfSandwichPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sizeOfSandwichPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sizeOfSandwichLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fourInchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sizeOfSandwichPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(twelveInchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eightInchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        premiumToppingPanel.setBackground(new java.awt.Color(200, 200, 200));

        preimumLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        preimumLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        preimumLabel.setText("Premium Toppings");

        hamButton.setText("Ham");
        hamButton.setFocusable(false);
        hamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hamButtonActionPerformed(evt);
            }
        });

        salamiButton.setText("Salami");
        salamiButton.setFocusable(false);
        salamiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salamiButtonActionPerformed(evt);
            }
        });

        steakButton.setText("Steak");
        steakButton.setFocusable(false);
        steakButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                steakButtonActionPerformed(evt);
            }
        });

        roastBeefButton.setText("Roast Beef");
        roastBeefButton.setFocusable(false);
        roastBeefButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roastBeefButtonActionPerformed(evt);
            }
        });

        chickenButton.setText("Chicken");
        chickenButton.setFocusable(false);
        chickenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chickenButtonActionPerformed(evt);
            }
        });

        baconButton.setText("Bacon");
        baconButton.setFocusable(false);
        baconButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baconButtonActionPerformed(evt);
            }
        });

        americanButton.setText("American");
        americanButton.setFocusable(false);
        americanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                americanButtonActionPerformed(evt);
            }
        });

        provoloneButton.setText("Provolone");
        provoloneButton.setFocusable(false);
        provoloneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provoloneButtonActionPerformed(evt);
            }
        });

        cheddarButton.setText("Cheddar");
        cheddarButton.setFocusable(false);
        cheddarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheddarButtonActionPerformed(evt);
            }
        });

        swissButton.setText("Swiss");
        swissButton.setFocusable(false);
        swissButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                swissButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout premiumToppingPanelLayout = new javax.swing.GroupLayout(premiumToppingPanel);
        premiumToppingPanel.setLayout(premiumToppingPanelLayout);
        premiumToppingPanelLayout.setHorizontalGroup(
            premiumToppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(premiumToppingPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(premiumToppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, premiumToppingPanelLayout.createSequentialGroup()
                        .addGroup(premiumToppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(premiumToppingPanelLayout.createSequentialGroup()
                                .addComponent(chickenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2))
                            .addGroup(premiumToppingPanelLayout.createSequentialGroup()
                                .addComponent(americanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(provoloneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(premiumToppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(premiumToppingPanelLayout.createSequentialGroup()
                                .addComponent(cheddarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(swissButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(premiumToppingPanelLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(baconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, premiumToppingPanelLayout.createSequentialGroup()
                        .addComponent(preimumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, premiumToppingPanelLayout.createSequentialGroup()
                        .addComponent(steakButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(salamiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(roastBeefButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 14, Short.MAX_VALUE))
        );
        premiumToppingPanelLayout.setVerticalGroup(
            premiumToppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(premiumToppingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(preimumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(premiumToppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salamiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roastBeefButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(steakButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(premiumToppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chickenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(baconButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(premiumToppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(americanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(provoloneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cheddarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(swissButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        regularToppingPanel.setBackground(new java.awt.Color(200, 200, 200));

        regularLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        regularLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regularLabel1.setText("Regular Toppings");

        lettuceButton.setText("Lettuce");
        lettuceButton.setFocusable(false);
        lettuceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lettuceButtonActionPerformed(evt);
            }
        });

        pepperButton.setText("Peppers");
        pepperButton.setFocusable(false);
        pepperButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pepperButtonActionPerformed(evt);
            }
        });

        onionButton.setText("Onions");
        onionButton.setFocusable(false);
        onionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onionButtonActionPerformed(evt);
            }
        });

        tomatoButton.setText("Tomatoes");
        tomatoButton.setFocusable(false);
        tomatoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomatoButtonActionPerformed(evt);
            }
        });

        jalepenoButton.setText("Jalepenos");
        jalepenoButton.setFocusable(false);
        jalepenoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jalepenoButtonActionPerformed(evt);
            }
        });

        cucumberButton.setText("Cucumbers");
        cucumberButton.setFocusable(false);
        cucumberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cucumberButtonActionPerformed(evt);
            }
        });

        pickleButton.setText("Pickles");
        pickleButton.setFocusable(false);
        pickleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickleButtonActionPerformed(evt);
            }
        });

        guacamoleButton.setText("Guacamole");
        guacamoleButton.setFocusable(false);
        guacamoleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guacamoleButtonActionPerformed(evt);
            }
        });

        mushroomButton.setText("Mushrooms");
        mushroomButton.setFocusable(false);
        mushroomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mushroomButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout regularToppingPanelLayout = new javax.swing.GroupLayout(regularToppingPanel);
        regularToppingPanel.setLayout(regularToppingPanelLayout);
        regularToppingPanelLayout.setHorizontalGroup(
            regularToppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regularToppingPanelLayout.createSequentialGroup()
                .addGroup(regularToppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(regularToppingPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(regularLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(regularToppingPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lettuceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pepperButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(onionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tomatoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(regularToppingPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jalepenoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cucumberButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pickleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guacamoleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(regularToppingPanelLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(mushroomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        regularToppingPanelLayout.setVerticalGroup(
            regularToppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regularToppingPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(regularLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(regularToppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lettuceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pepperButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(onionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tomatoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(regularToppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(regularToppingPanelLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(regularToppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jalepenoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cucumberButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(regularToppingPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(regularToppingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guacamoleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pickleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mushroomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        saucePanel.setBackground(new java.awt.Color(200, 200, 200));

        regularLabel2.setBackground(java.awt.Color.lightGray);
        regularLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        regularLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regularLabel2.setText("Sauces");

        mayoButton.setText("Mayo");
        mayoButton.setFocusable(false);
        mayoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mayoButtonActionPerformed(evt);
            }
        });

        mustardButton.setText("Mustard");
        mustardButton.setFocusable(false);
        mustardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mustardButtonActionPerformed(evt);
            }
        });

        ketchupButton.setText("Ketchup");
        ketchupButton.setFocusable(false);
        ketchupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ketchupButtonActionPerformed(evt);
            }
        });

        islandButton.setText("Thousand Island");
        islandButton.setFocusable(false);
        islandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                islandButtonActionPerformed(evt);
            }
        });

        ranchButton.setText("Ranch");
        ranchButton.setFocusable(false);
        ranchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ranchButtonActionPerformed(evt);
            }
        });

        vinaigretteButton.setText("Vinaigrette");
        vinaigretteButton.setFocusable(false);
        vinaigretteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vinaigretteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout saucePanelLayout = new javax.swing.GroupLayout(saucePanel);
        saucePanel.setLayout(saucePanelLayout);
        saucePanelLayout.setHorizontalGroup(
            saucePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, saucePanelLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(regularLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(saucePanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(mayoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(mustardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ketchupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(saucePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(ranchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(islandButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(vinaigretteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        saucePanelLayout.setVerticalGroup(
            saucePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saucePanelLayout.createSequentialGroup()
                .addComponent(regularLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(saucePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mayoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mustardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ketchupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(saucePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(islandButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ranchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vinaigretteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        toastedPanel.setBackground(new java.awt.Color(200, 200, 200));

        regularLabel.setBackground(java.awt.Color.lightGray);
        regularLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        regularLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regularLabel.setText("Toasted?");

        noToastedButton.setText("No");
        noToastedButton.setFocusable(false);
        noToastedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noToastedButtonActionPerformed(evt);
            }
        });

        yesToastedButton.setText("Yes");
        yesToastedButton.setFocusable(false);
        yesToastedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesToastedButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout toastedPanelLayout = new javax.swing.GroupLayout(toastedPanel);
        toastedPanel.setLayout(toastedPanelLayout);
        toastedPanelLayout.setHorizontalGroup(
            toastedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toastedPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(regularLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toastedPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(yesToastedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(noToastedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        toastedPanelLayout.setVerticalGroup(
            toastedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toastedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(regularLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(toastedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yesToastedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noToastedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        addSandwich.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        addSandwich.setText("Add to Order");

        sandwichMenu.setLayer(typeOfBreadPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        sandwichMenu.setLayer(sizeOfSandwichPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        sandwichMenu.setLayer(premiumToppingPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        sandwichMenu.setLayer(regularToppingPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        sandwichMenu.setLayer(saucePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        sandwichMenu.setLayer(toastedPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        sandwichMenu.setLayer(addSandwich, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout sandwichMenuLayout = new javax.swing.GroupLayout(sandwichMenu);
        sandwichMenu.setLayout(sandwichMenuLayout);
        sandwichMenuLayout.setHorizontalGroup(
            sandwichMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sandwichMenuLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(sandwichMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(premiumToppingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(typeOfBreadPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toastedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(sandwichMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saucePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regularToppingPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sizeOfSandwichPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
            .addGroup(sandwichMenuLayout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(addSandwich, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sandwichMenuLayout.setVerticalGroup(
            sandwichMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sandwichMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sandwichMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(typeOfBreadPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sizeOfSandwichPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sandwichMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sandwichMenuLayout.createSequentialGroup()
                        .addComponent(premiumToppingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(toastedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sandwichMenuLayout.createSequentialGroup()
                        .addComponent(regularToppingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saucePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addComponent(addSandwich, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        buttonMenu.setLayer(sandwichButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        buttonMenu.setLayer(chipsButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        buttonMenu.setLayer(drinkButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        buttonMenu.setLayer(checkoutButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        buttonMenu.setLayer(sandwichMenu, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout buttonMenuLayout = new javax.swing.GroupLayout(buttonMenu);
        buttonMenu.setLayout(buttonMenuLayout);
        buttonMenuLayout.setHorizontalGroup(
            buttonMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonMenuLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(buttonMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(sandwichButton, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(drinkButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chipsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sandwichMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        buttonMenuLayout.setVerticalGroup(
            buttonMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonMenuLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(buttonMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sandwichMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(buttonMenuLayout.createSequentialGroup()
                        .addComponent(sandwichButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(drinkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(chipsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(372, 372, 372)
                        .addComponent(checkoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sandwichMenu.setVisible(false);

        allButtons.setLayer(emptyMenu, javax.swing.JLayeredPane.DEFAULT_LAYER);
        allButtons.setLayer(buttonMenu, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout allButtonsLayout = new javax.swing.GroupLayout(allButtons);
        allButtons.setLayout(allButtonsLayout);
        allButtonsLayout.setHorizontalGroup(
            allButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allButtonsLayout.createSequentialGroup()
                .addComponent(buttonMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emptyMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
        );
        allButtonsLayout.setVerticalGroup(
            allButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonMenu)
            .addGroup(allButtonsLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(emptyMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        emptyMenu.setVisible(true);

        jLayeredPane1.setLayer(orderContainer, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(allButtons, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(orderContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(allButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 1240, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(allButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(orderContainer)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Sandwich.SandwichSize sandwichSize;
    private Sandwich.BreadType breadType;
    boolean hasExtra;
    private ArrayList<Topping> toppings = new ArrayList<>();
    private boolean isToasted;

    private void sandwichButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sandwichButtonActionPerformed
        if (sandwichMenu.isVisible()) {
            //Turning off sandwich mode
            sandwichMenu.setVisible(false);
            emptyMenu.setVisible(true);
            drinkButton.setEnabled(true);
            chipsButton.setEnabled(true);
            checkoutButton.setEnabled(true);
        } else {
            //turning on sandwich mode
            sandwichMenu.setVisible(true);
            emptyMenu.setVisible(false);
            drinkButton.setEnabled(false);
            chipsButton.setEnabled(false);
            checkoutButton.setEnabled(false);
        }
    }//GEN-LAST:event_sandwichButtonActionPerformed

    private void addSandwichToOrder() {
        order.addItem(new Sandwich(sandwichSize, isToasted, breadType, toppings));
    }

    private void whiteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whiteButtonActionPerformed

    }//GEN-LAST:event_whiteButtonActionPerformed

    private void ryeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ryeButtonActionPerformed

    }//GEN-LAST:event_ryeButtonActionPerformed

    private void noToastedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noToastedButtonActionPerformed
        isToasted = false;
    }//GEN-LAST:event_noToastedButtonActionPerformed

    private void yesToastedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesToastedButtonActionPerformed
        isToasted = true;
    }//GEN-LAST:event_yesToastedButtonActionPerformed

    Meat meat;

    private void addMeat(JToggleButton button, Meat.TypeOfMeat typeOfMeat) {
        if (button.isSelected()) {
            int extra = JOptionPane.showConfirmDialog(sandwichMenu, "Does the customer want extra?", "Extra", JOptionPane.YES_NO_OPTION);
            if (extra == 0) {
                meat = new Meat(typeOfMeat, sandwichSize, true);
                toppings.add(meat);
            } else {
                meat = new Meat(typeOfMeat, sandwichSize, false);
                toppings.add(meat);
            }
        } else {
            toppings.removeIf(t -> ((Meat) t).getTypeOfMeat() == typeOfMeat);
        }
        toppings.stream().forEach(t -> System.out.println(t.toString()));
    }

    Cheese cheese;

    private void addCheese(JToggleButton button, Cheese.TypeOfCheese typeOfCheese) {
        if (button.isSelected()) {
            int extra = JOptionPane.showConfirmDialog(sandwichMenu, "Does the customer want extra?", "Extra", JOptionPane.YES_NO_OPTION);
            if (extra == 0) {
                cheese = new Cheese(typeOfCheese, sandwichSize, true);
                toppings.add(cheese);
            } else {
                cheese = new Cheese(typeOfCheese, sandwichSize, false);
                toppings.add(cheese);
            }
        } else {
            toppings.removeIf(t -> ((Cheese) t).getTypeOfCheese() == typeOfCheese);
        }
        toppings.stream().forEach(t -> System.out.println(t.toString()));
    }

    RegularTopping regTopping;

    private void addRegTopping(JToggleButton button, RegularToppings topping) {
        if (button.isSelected()) {
            int extra = JOptionPane.showConfirmDialog(sandwichMenu, "Does the customer want extra?", "Extra", JOptionPane.YES_NO_OPTION);
            if (extra == 0) {
                regTopping = new RegularTopping(true, sandwichSize, topping);
                toppings.add(regTopping);
            } else {
                regTopping = new RegularTopping(false, sandwichSize, topping);
                toppings.add(regTopping);
            }
        } else {
            toppings.removeIf(t-> ((RegularTopping) t).getRegularTopping() == topping);

        }
        toppings.stream().forEach(t -> System.out.println(t.toString()));
    }

    private void steakButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_steakButtonActionPerformed
        addMeat(steakButton, Meat.TypeOfMeat.STEAK);
    }//GEN-LAST:event_steakButtonActionPerformed

    private void baconButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baconButtonActionPerformed
        addMeat(baconButton, Meat.TypeOfMeat.BACON);
    }//GEN-LAST:event_baconButtonActionPerformed

    private void americanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_americanButtonActionPerformed
        addCheese(americanButton, Cheese.TypeOfCheese.AMERICAN);
    }//GEN-LAST:event_americanButtonActionPerformed

    private void provoloneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provoloneButtonActionPerformed
        addCheese(provoloneButton, Cheese.TypeOfCheese.PROVOLONE);
    }//GEN-LAST:event_provoloneButtonActionPerformed

    private void cheddarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheddarButtonActionPerformed
        addCheese(cheddarButton, Cheese.TypeOfCheese.CHEDDAR);
    }//GEN-LAST:event_cheddarButtonActionPerformed

    private void swissButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_swissButtonActionPerformed
        addCheese(swissButton, Cheese.TypeOfCheese.SWISS);
    }//GEN-LAST:event_swissButtonActionPerformed


    private void tomatoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomatoButtonActionPerformed
        addRegTopping(tomatoButton, RegularToppings.TOMATOES);
    }//GEN-LAST:event_tomatoButtonActionPerformed

    private void onionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onionButtonActionPerformed
        addRegTopping(onionButton, RegularToppings.ONIONS);
    }//GEN-LAST:event_onionButtonActionPerformed

    private void pepperButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pepperButtonActionPerformed
        addRegTopping(pepperButton, RegularToppings.PEPPERS);
    }//GEN-LAST:event_pepperButtonActionPerformed

    private void lettuceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lettuceButtonActionPerformed
        addRegTopping(lettuceButton, RegularToppings.LETTUCE);
    }//GEN-LAST:event_lettuceButtonActionPerformed

    private void jalepenoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jalepenoButtonActionPerformed
        addRegTopping(jalepenoButton, RegularToppings.JALEPENOS);
    }//GEN-LAST:event_jalepenoButtonActionPerformed

    private void cucumberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cucumberButtonActionPerformed
        addRegTopping(cucumberButton, RegularToppings.CUCUMBERS);
    }//GEN-LAST:event_cucumberButtonActionPerformed

    private void pickleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickleButtonActionPerformed
        addRegTopping(pickleButton, RegularToppings.PICKLES);
    }//GEN-LAST:event_pickleButtonActionPerformed

    private void guacamoleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guacamoleButtonActionPerformed
        addRegTopping(guacamoleButton, RegularToppings.GUACAMOLE);
    }//GEN-LAST:event_guacamoleButtonActionPerformed

    private void mushroomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mushroomButtonActionPerformed
        addRegTopping(mushroomButton, RegularToppings.MUSHROOMS);
    }//GEN-LAST:event_mushroomButtonActionPerformed

    private void mayoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mayoButtonActionPerformed
        addRegTopping(mayoButton, RegularToppings.MAYO);
    }//GEN-LAST:event_mayoButtonActionPerformed

    private void mustardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mustardButtonActionPerformed
        addRegTopping(mustardButton, RegularToppings.MUSTARD);
    }//GEN-LAST:event_mustardButtonActionPerformed

    private void ketchupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ketchupButtonActionPerformed
        addRegTopping(ketchupButton, RegularToppings.KETCHUP);
    }//GEN-LAST:event_ketchupButtonActionPerformed

    private void islandButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_islandButtonActionPerformed
        addRegTopping(islandButton, RegularToppings.THOUSAND_ISLAND);
    }//GEN-LAST:event_islandButtonActionPerformed

    private void ranchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ranchButtonActionPerformed
        addRegTopping(ranchButton, RegularToppings.RANCH);
    }//GEN-LAST:event_ranchButtonActionPerformed

    private void vinaigretteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vinaigretteButtonActionPerformed
        addRegTopping(vinaigretteButton, RegularToppings.VINAIGRETTE);
    }//GEN-LAST:event_vinaigretteButtonActionPerformed

    private void hamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hamButtonActionPerformed
        addMeat(hamButton, Meat.TypeOfMeat.HAM);
    }//GEN-LAST:event_hamButtonActionPerformed

    private void salamiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salamiButtonActionPerformed
        addMeat(salamiButton, Meat.TypeOfMeat.SALAMI);
    }//GEN-LAST:event_salamiButtonActionPerformed

    private void roastBeefButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roastBeefButtonActionPerformed
        addMeat(roastBeefButton, Meat.TypeOfMeat.ROAST_BEEF);
    }//GEN-LAST:event_roastBeefButtonActionPerformed

    private void chickenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chickenButtonActionPerformed
        addMeat(chickenButton, Meat.TypeOfMeat.CHICKEN);
    }//GEN-LAST:event_chickenButtonActionPerformed


    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSandwich;
    private javax.swing.JLayeredPane allButtons;
    private javax.swing.JToggleButton americanButton;
    private javax.swing.JToggleButton baconButton;
    private javax.swing.JLayeredPane buttonMenu;
    private javax.swing.JButton checkoutButton;
    private javax.swing.JToggleButton cheddarButton;
    private javax.swing.JToggleButton chickenButton;
    private javax.swing.JButton chipsButton;
    private javax.swing.JToggleButton cucumberButton;
    private javax.swing.JButton drinkButton;
    private javax.swing.JButton eightInchButton;
    private javax.swing.JLayeredPane emptyMenu;
    private javax.swing.JButton fourInchButton;
    private javax.swing.JToggleButton guacamoleButton;
    private javax.swing.JToggleButton hamButton;
    private javax.swing.JToggleButton islandButton;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JToggleButton jalepenoButton;
    private javax.swing.JToggleButton ketchupButton;
    private javax.swing.JToggleButton lettuceButton;
    private javax.swing.JToggleButton mayoButton;
    private javax.swing.JToggleButton mushroomButton;
    private javax.swing.JToggleButton mustardButton;
    private javax.swing.JButton noToastedButton;
    private javax.swing.JToggleButton onionButton;
    private javax.swing.JScrollPane orderContainer;
    private javax.swing.JToggleButton pepperButton;
    private javax.swing.JToggleButton pickleButton;
    private javax.swing.JLabel preimumLabel;
    private javax.swing.JPanel premiumToppingPanel;
    private javax.swing.JToggleButton provoloneButton;
    private javax.swing.JToggleButton ranchButton;
    private javax.swing.JLabel regularLabel;
    private javax.swing.JLabel regularLabel1;
    private javax.swing.JLabel regularLabel2;
    private javax.swing.JPanel regularToppingPanel;
    private javax.swing.JToggleButton roastBeefButton;
    private javax.swing.JButton ryeButton;
    private javax.swing.JToggleButton salamiButton;
    private javax.swing.JButton sandwichButton;
    private javax.swing.JLayeredPane sandwichMenu;
    private javax.swing.JPanel saucePanel;
    private javax.swing.JLabel sizeOfSandwichLabel;
    private javax.swing.JPanel sizeOfSandwichPanel;
    private javax.swing.JToggleButton steakButton;
    private javax.swing.JToggleButton swissButton;
    private javax.swing.JPanel toastedPanel;
    private javax.swing.JToggleButton tomatoButton;
    private javax.swing.JButton twelveInchButton;
    private javax.swing.JLabel typeOfBreadLabel;
    private javax.swing.JPanel typeOfBreadPanel;
    private javax.swing.JToggleButton vinaigretteButton;
    private javax.swing.JButton wheatButton;
    private javax.swing.JButton whiteButton;
    private javax.swing.JButton wrapButton;
    private javax.swing.JButton yesToastedButton;
    // End of variables declaration//GEN-END:variables
}
