/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pluralsight.delishop.userinterface.loginscreen;

import com.pluralsight.delishop.userinterface.mainscreen.MainScreen;

import javax.swing.*;

/**
 * @author proco
 */
public class UserPassScreen extends javax.swing.JFrame {

    private String password;
    private StringBuilder sb;

    /**
     * Creates new form UserPassScreen1
     */
    public UserPassScreen() {
        password = "12345";
        sb = new StringBuilder();
        initComponents();

//        setResizable(false);


        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserPassScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserPassScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserPassScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserPassScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            this.setVisible(true);
            this.setLocationRelativeTo(null);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JLayeredPane();
        heading = new javax.swing.JLabel();
        buttonContainer = new javax.swing.JLayeredPane();
        emptyLabel = new javax.swing.JLabel();
        button0 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log in please :D");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(42, 86, 28));

        Background.setBackground(new java.awt.Color(157, 220, 101));
        Background.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(42, 86, 28), 30, true));
        Background.setOpaque(true);
        Background.setPreferredSize(new java.awt.Dimension(1920, 1080));

        heading.setFont(new java.awt.Font("Segoe UI", 1, 72)); // NOI18N
        heading.setText("Enter 5-Digit Employee Password");

        buttonContainer.setLayout(new java.awt.GridLayout(4, 3));


        for(int i = 1; i <= 9; i++){
            JButton button = new JButton();
            button.setBackground(new java.awt.Color(153, 153, 153));
            button.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
            button.setText(String.valueOf(i));
            button.setAlignmentY(0.0F);
            button.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
            button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            button.setFocusable(false);
            button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            button.setSelected(true);
            int finalI = i;
            button.addActionListener(evt -> handleButtonPress(finalI));
            buttonContainer.add(button);
        }

        emptyLabel.setFocusable(false);
        buttonContainer.add(emptyLabel);

        button0.setBackground(new java.awt.Color(153, 153, 153));
        button0.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
        button0.setText("0");
        button0.setAlignmentY(0.0F);
        button0.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        button0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button0.setFocusable(false);
        button0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button0.setSelected(true);
        button0.addActionListener(evt -> handleButtonPress(0));
        buttonContainer.add(button0);

        Background.setLayer(heading, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Background.setLayer(buttonContainer, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addGap(404, 404, 404)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(buttonContainer)
                    .addComponent(heading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(404, 404, 404))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(heading)
                .addGap(28, 28, 28)
                .addComponent(buttonContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(268, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 1043, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void handleButtonPress(int number) {
        sb.append(number);
        if (sb.length() % 5 == 0 && password.equalsIgnoreCase(sb.toString())) {
            new MainScreen();
            this.dispose();
        } else if (sb.length() % 5 == 0) {
            sb = new StringBuilder();  //Resets string
            JOptionPane.showMessageDialog(buttonContainer, "Incorrect Password, Please enter again", "Incorrect Password", JOptionPane.WARNING_MESSAGE); // Adds popup to reenter the
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane Background;
    private javax.swing.JButton button0;
    private javax.swing.JLayeredPane buttonContainer;
    private javax.swing.JLabel emptyLabel;
    private javax.swing.JLabel heading;
    // End of variables declaration//GEN-END:variables
}
